// frontend/src/lib/components/panel/config/KeyValueEditor.svelte
<script lang="ts">
	let {
		entries = $bindable<{ key: string; value: string }[]>([]),
		keyPlaceholder = 'Key',
		valuePlaceholder = 'Value',
		onchange,
	}: {
		entries: { key: string; value: string }[];
		keyPlaceholder?: string;
		valuePlaceholder?: string;
		onchange?: () => void;
	} = $props();

	function addEntry() {
		entries = [...entries, { key: '', value: '' }];
		onchange?.();
	}

	function removeEntry(index: number) {
		entries = entries.filter((_, i) => i !== index);
		onchange?.();
	}
</script>

<div class="space-y-1">
	{#each entries as entry, i}
		<div class="flex items-center gap-1">
			<input
				class="flex-1 rounded border border-gray-300 px-2 py-1 text-xs focus:border-blue-500 focus:outline-none"
				placeholder={keyPlaceholder}
				bind:value={entry.key}
				oninput={() => onchange?.()}
			/>
			<input
				class="flex-1 rounded border border-gray-300 px-2 py-1 text-xs focus:border-blue-500 focus:outline-none"
				placeholder={valuePlaceholder}
				bind:value={entry.value}
				oninput={() => onchange?.()}
			/>
			<button
				class="text-gray-400 hover:text-red-500"
				onclick={() => removeEntry(i)}
				aria-label="Remove entry"
			>
				<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
				</svg>
			</button>
		</div>
	{/each}
	<button class="text-xs text-blue-600 hover:text-blue-700" onclick={addEntry}>
		+ Add
	</button>
</div>

// frontend/src/components/KeyValueEditor.tsx
import { Input } from '@/components/ui/input';
import { X } from 'lucide-react';

interface Entry {
  key: string;
  value: string;
}

interface KeyValueEditorProps {
  entries: Entry[];
  onChange: (entries: Entry[]) => void;
  keyPlaceholder?: string;
  valuePlaceholder?: string;
}

export default function KeyValueEditor({
  entries,
  onChange,
  keyPlaceholder = 'Key',
  valuePlaceholder = 'Value',
}: KeyValueEditorProps) {
  function addEntry() {
    onChange([...entries, { key: '', value: '' }]);
  }

  function removeEntry(index: number) {
    onChange(entries.filter((_, i) => i !== index));
  }

  function updateEntry(index: number, field: 'key' | 'value', val: string) {
    onChange(entries.map((e, i) => (i === index ? { ...e, [field]: val } : e)));
  }

  return (
    <div className="space-y-1">
      {entries.map((entry, i) => (
        <div key={i} className="flex items-center gap-1">
          <Input
            className="flex-1 text-xs"
            placeholder={keyPlaceholder}
            value={entry.key}
            onChange={(e) => updateEntry(i, 'key', e.target.value)}
          />
          <Input
            className="flex-1 text-xs"
            placeholder={valuePlaceholder}
            value={entry.value}
            onChange={(e) => updateEntry(i, 'value', e.target.value)}
          />
          <button
            className="text-gray-400 hover:text-red-500"
            onClick={() => removeEntry(i)}
            aria-label="Remove entry"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      ))}
      <button className="text-xs text-blue-600 hover:text-blue-700" onClick={addEntry}>
        + Add
      </button>
    </div>
  );
}
