// frontend/src/lib/components/QueryEditor.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { updatePipelineQuery, pipelineStore } from '$lib/stores/pipeline.js';
	import { debounce } from '$lib/utils/debounce.js';
	import SqlEditor from '$lib/components/panel/config/SqlEditor.svelte';

	let {
		pipelineId,
		onRun,
	}: {
		pipelineId: string;
		onRun: () => void;
	} = $props();

	let queryValue = $state($pipelineStore.pipeline?.query ?? '');

	// Sync from store when pipeline loads (untrack queryValue so typing doesn't re-trigger)
	$effect(() => {
		const pipelineQuery = $pipelineStore.pipeline?.query ?? '';
		if (pipelineQuery !== untrack(() => queryValue)) {
			queryValue = pipelineQuery;
		}
	});

	const saveQuery = debounce((...args: unknown[]) => {
		updatePipelineQuery(pipelineId, args[0] as string);
	}, 800);

	let sqlEditor: SqlEditor | undefined = $state();

	function handleQueryChange(newValue: string) {
		queryValue = newValue;
		saveQuery(newValue);
	}

	function handleRun() {
		saveQuery.cancel();
		updatePipelineQuery(pipelineId, queryValue).then(() => {
			onRun();
		});
	}

	export function setSql(sql: string) {
		queryValue = sql;
		saveQuery(sql);
	}
</script>

<div class="flex h-full flex-col" data-testid="query-editor">
	<!-- Header bar -->
	<div class="flex items-center justify-between border-b border-gray-200 px-3 py-2">
		<h3 class="text-xs font-semibold uppercase tracking-wide text-gray-500">SQL Query</h3>
		<span class="text-xs text-gray-400">
			{navigator.platform.includes('Mac') ? '\u2318' : 'Ctrl'}+Enter to run
		</span>
	</div>

	<!-- SQL editor -->
	<div class="flex-1 overflow-auto p-2">
		<SqlEditor
			bind:this={sqlEditor}
			bind:value={queryValue}
			onRunPreview={handleRun}
			onchange={handleQueryChange}
			placeholder="SELECT * FROM my_table..."
		/>
	</div>
</div>

// frontend/src/components/QueryEditor.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { usePipelineStore } from '@/stores/pipeline';
import { debounce } from '@/utils/debounce';
import SqlEditor from './SqlEditor';

interface QueryEditorProps {
  pipelineId: string;
  onRun: () => void;
  onSqlRef?: (setter: (sql: string) => void) => void;
}

export default function QueryEditor({ pipelineId, onRun, onSqlRef }: QueryEditorProps) {
  const pipelineQuery = usePipelineStore((s) => s.pipeline?.query ?? '');
  const updatePipelineQuery = usePipelineStore((s) => s.updatePipelineQuery);
  const [queryValue, setQueryValue] = useState(pipelineQuery);
  const queryValueRef = useRef(queryValue);
  queryValueRef.current = queryValue;

  // Sync from store when pipeline loads
  useEffect(() => {
    if (pipelineQuery !== queryValueRef.current) {
      setQueryValue(pipelineQuery);
    }
  }, [pipelineQuery]);

  const saveQuery = useMemo(
    () =>
      debounce((...args: unknown[]) => {
        updatePipelineQuery(pipelineId, args[0] as string);
      }, 800),
    [pipelineId, updatePipelineQuery],
  );

  const handleQueryChange = useCallback(
    (newValue: string) => {
      setQueryValue(newValue);
      saveQuery(newValue);
    },
    [saveQuery],
  );

  const handleRun = useCallback(() => {
    saveQuery.cancel();
    updatePipelineQuery(pipelineId, queryValueRef.current).then(() => {
      onRun();
    });
  }, [pipelineId, updatePipelineQuery, onRun, saveQuery]);

  // Expose setSql to parent
  useEffect(() => {
    onSqlRef?.((sql: string) => {
      setQueryValue(sql);
      saveQuery(sql);
    });
  }, [onSqlRef, saveQuery]);

  return (
    <div className="flex h-full flex-col" data-testid="query-editor">
      <div className="flex items-center justify-between border-b border-gray-200 px-3 py-2">
        <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500">SQL Query</h3>
        <span className="text-xs text-gray-400">
          {navigator.platform.includes('Mac') ? '\u2318' : 'Ctrl'}+Enter to run
        </span>
      </div>
      <div className="flex-1 overflow-auto p-2">
        <SqlEditor
          value={queryValue}
          onChange={handleQueryChange}
          onRunPreview={handleRun}
          placeholder="SELECT * FROM my_table..."
        />
      </div>
    </div>
  );
}
