// frontend/src/lib/components/ResultsPanel.svelte
<script lang="ts">
	import { resultsStore } from '$lib/stores/results.js';
	import { runsStore, loadRuns, loadRunDetail } from '$lib/stores/runs.js';
	import {
		cteInspectionStore,
		loadCteInspection,
		selectCte,
	} from '$lib/stores/cteInspection.js';
	import {
		sourcePreviewStore,
		loadSourcePreview,
		selectSource,
	} from '$lib/stores/sourcePreview.js';
	import { api } from '$lib/api/client.js';
	import DataViewer from './DataViewer.svelte';

	let {
		pipelineId,
		activeTab = $bindable('results'),
	}: {
		pipelineId: string;
		activeTab: string;
	} = $props();

	// Run history
	let expandedRunId = $state<string | null>(null);

	function toggleExpand(runId: string) {
		if (expandedRunId === runId) {
			expandedRunId = null;
		} else {
			expandedRunId = runId;
			loadRunDetail(pipelineId, runId);
		}
	}

	function formatTime(iso: string): string {
		return new Date(iso).toLocaleString();
	}

	function downloadUrl(runId: string, format: 'csv' | 'json'): string {
		return api.download.url(pipelineId, runId, format);
	}

	// Source preview: selected source data
	let selectedSourceData = $derived(
		$sourcePreviewStore.sources.find((s) => s.name === $sourcePreviewStore.selectedSource) ?? null
	);

	// CTE inspection: selected CTE data
	let selectedCteData = $derived(
		$cteInspectionStore.ctes.find((c) => c.name === $cteInspectionStore.selectedCte) ?? null
	);

	// Cache is stale when the runId has changed since last CTE fetch
	let cteStale = $derived(
		$resultsStore.runId !== $cteInspectionStore.cachedForRunId
	);

	$effect(() => {
		if (activeTab === 'history') {
			loadRuns(pipelineId);
		}
		if (activeTab === 'inputs' && !$sourcePreviewStore.cached && !$sourcePreviewStore.loading) {
			loadSourcePreview(pipelineId);
		}
		if (activeTab === 'ctes' && cteStale && !$cteInspectionStore.loading) {
			loadCteInspection(pipelineId, $resultsStore.runId);
		}
	});
</script>

<div class="flex h-full flex-col">
	<!-- Tab bar -->
	<div class="flex gap-0 border-b border-gray-200 px-2">
		<button
			data-testid="tab-inputs"
			class="px-3 py-1.5 text-xs font-medium transition-colors {activeTab === 'inputs'
				? 'border-b-2 border-blue-500 text-blue-600'
				: 'text-gray-500 hover:text-gray-700'}"
			onclick={() => (activeTab = 'inputs')}
		>
			Inputs
		</button>
		<button
			data-testid="tab-ctes"
			class="px-3 py-1.5 text-xs font-medium transition-colors {activeTab === 'ctes'
				? 'border-b-2 border-blue-500 text-blue-600'
				: 'text-gray-500 hover:text-gray-700'}"
			onclick={() => (activeTab = 'ctes')}
		>
			Intermediate CTEs
		</button>
		<button
			data-testid="tab-results"
			class="px-3 py-1.5 text-xs font-medium transition-colors {activeTab === 'results'
				? 'border-b-2 border-blue-500 text-blue-600'
				: 'text-gray-500 hover:text-gray-700'}"
			onclick={() => (activeTab = 'results')}
		>
			Results
		</button>
		<button
			data-testid="tab-history"
			class="ml-auto px-3 py-1.5 text-xs font-medium transition-colors {activeTab === 'history'
				? 'border-b-2 border-blue-500 text-blue-600'
				: 'text-gray-500 hover:text-gray-700'}"
			onclick={() => (activeTab = 'history')}
		>
			Run History
		</button>
	</div>

	<!-- Content -->
	<div class="flex flex-1 flex-col overflow-hidden {activeTab === 'history' ? 'overflow-y-auto' : ''}">
		{#if activeTab === 'inputs'}
			<!-- Source Inputs -->
			{#if $sourcePreviewStore.loading}
				<div class="flex h-full items-center justify-center text-sm text-gray-500">
					<svg class="mr-2 h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<circle cx="12" cy="12" r="10" class="opacity-25" />
						<path d="M4 12a8 8 0 0 1 8-8" class="opacity-75" stroke-linecap="round" />
					</svg>
					Loading sources...
				</div>
			{:else if $sourcePreviewStore.error}
				<div class="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{$sourcePreviewStore.error}</div>
			{:else if $sourcePreviewStore.sources.length === 0}
				<div class="flex h-full items-center justify-center text-sm text-gray-400">
					No sources configured.
				</div>
			{:else}
				<!-- Source selector pills -->
				<div class="flex shrink-0 items-center gap-1.5 overflow-x-auto border-b border-gray-200 bg-white px-3 py-1.5">
					{#each $sourcePreviewStore.sources as src}
						<button
							class="shrink-0 rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors {$sourcePreviewStore.selectedSource === src.name
								? 'bg-blue-100 text-blue-700'
								: 'bg-gray-100 text-gray-600 hover:bg-gray-200'}"
							onclick={() => selectSource(src.name)}
						>
							{src.name}
							<span class="ml-1 text-gray-400">{src.row_count}</span>
						</button>
					{/each}
					{#if $sourcePreviewStore.durationMs != null}
						<span class="ml-auto shrink-0 text-xs text-gray-400">{$sourcePreviewStore.durationMs}ms</span>
					{/if}
				</div>
				<!-- Source data viewer -->
				{#if selectedSourceData}
					{#if selectedSourceData.error}
						<div class="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{selectedSourceData.error}</div>
					{:else}
						{#key $sourcePreviewStore.selectedSource}
							<DataViewer data={selectedSourceData.data} schema={selectedSourceData.schema_info} />
						{/key}
					{/if}
				{/if}
			{/if}
		{:else if activeTab === 'ctes'}
			<!-- CTE Inspection -->
			{#if $cteInspectionStore.loading}
				<div class="flex h-full items-center justify-center text-sm text-gray-500">
					<svg class="mr-2 h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<circle cx="12" cy="12" r="10" class="opacity-25" />
						<path d="M4 12a8 8 0 0 1 8-8" class="opacity-75" stroke-linecap="round" />
					</svg>
					Inspecting CTEs...
				</div>
			{:else if $cteInspectionStore.error}
				<div class="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{$cteInspectionStore.error}</div>
			{:else if $cteInspectionStore.ctes.length === 0}
				<div class="flex h-full items-center justify-center text-sm text-gray-400">
					No CTEs found in the query.
				</div>
			{:else}
				<!-- CTE selector pills -->
				<div class="flex shrink-0 items-center gap-1.5 overflow-x-auto border-b border-gray-200 bg-white px-3 py-1.5">
					{#each $cteInspectionStore.ctes as cte}
						<button
							class="shrink-0 rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors {$cteInspectionStore.selectedCte === cte.name
								? 'bg-blue-100 text-blue-700'
								: 'bg-gray-100 text-gray-600 hover:bg-gray-200'}"
							onclick={() => selectCte(cte.name)}
						>
							{cte.name}
							<span class="ml-1 text-gray-400">{cte.row_count}</span>
						</button>
					{/each}
					{#if $cteInspectionStore.durationMs != null}
						<span class="ml-auto shrink-0 text-xs text-gray-400">{$cteInspectionStore.durationMs}ms</span>
					{/if}
				</div>
				<!-- CTE data viewer -->
				{#if selectedCteData}
					{#key $cteInspectionStore.selectedCte}
						<DataViewer data={selectedCteData.data} schema={selectedCteData.schema_info} />
					{/key}
				{/if}
			{/if}
		{:else if activeTab === 'results'}
			<!-- Results -->
			{#if $resultsStore.loading}
				<div class="flex h-full items-center justify-center text-sm text-gray-500">
					<svg class="mr-2 h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<circle cx="12" cy="12" r="10" class="opacity-25" />
						<path d="M4 12a8 8 0 0 1 8-8" class="opacity-75" stroke-linecap="round" />
					</svg>
					Running query...
				</div>
			{:else if $resultsStore.error}
				<div class="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{$resultsStore.error}</div>
			{:else if $resultsStore.data.length === 0}
				<div class="flex h-full items-center justify-center text-sm text-gray-400">
					No results yet. Click Run to execute the pipeline.
				</div>
			{:else}
				<!-- Results header bar -->
				<div class="flex shrink-0 items-center justify-between border-b border-gray-200 bg-white px-3 py-1">
					<span class="text-xs text-gray-500">
						Showing {$resultsStore.data.length} of {$resultsStore.rowCount ?? $resultsStore.data.length} rows
						{#if $resultsStore.durationMs != null}
							&middot; {$resultsStore.durationMs}ms
						{/if}
					</span>
					{#if $resultsStore.runId}
						<div class="flex gap-1.5" data-testid="download-buttons">
							<a
								href={downloadUrl($resultsStore.runId, 'csv')}
								class="rounded bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-700 hover:bg-gray-200"
								download
							>
								CSV
							</a>
							<a
								href={downloadUrl($resultsStore.runId, 'json')}
								class="rounded bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-700 hover:bg-gray-200"
								download
							>
								JSON
							</a>
						</div>
					{/if}
				</div>
				<DataViewer data={$resultsStore.data} schema={$resultsStore.schema} />
			{/if}
		{:else if activeTab === 'history'}
			<!-- Run History -->
			{#if $runsStore.loading}
				<div class="flex h-full items-center justify-center text-sm text-gray-500">Loading runs...</div>
			{:else if $runsStore.runs.length === 0}
				<div class="flex h-full items-center justify-center text-sm text-gray-400">
					No runs yet. Click Run to execute the pipeline.
				</div>
			{:else}
				<div class="divide-y divide-gray-100">
					{#each $runsStore.runs as run}
						<div>
							<button
								class="flex w-full items-center gap-3 px-3 py-2 text-left text-sm hover:bg-gray-50"
								onclick={() => toggleExpand(run.id)}
							>
								<span
									class="inline-block h-2 w-2 shrink-0 rounded-full {run.status === 'success'
										? 'bg-green-500'
										: 'bg-red-500'}"
								></span>
								<span class="flex-1 text-gray-700">{formatTime(run.started_at)}</span>
								<span class="text-xs text-gray-500">{run.duration_ms}ms</span>
								{#if run.row_count != null}
									<span class="text-xs text-gray-500">{run.row_count} rows</span>
								{/if}
								<svg
									class="h-3.5 w-3.5 text-gray-400 transition-transform {expandedRunId === run.id
										? 'rotate-180'
										: ''}"
									viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
								>
									<polyline points="6 9 12 15 18 9" />
								</svg>
							</button>

							{#if expandedRunId === run.id && $runsStore.expandedRun}
								<div class="border-t border-gray-100 bg-gray-50/50 px-4 py-3 text-xs">
									{#if $runsStore.expandedRun.error}
										<div class="mb-2 space-y-1 rounded bg-red-50 p-2 text-red-600">
											<div>{$runsStore.expandedRun.error.message}</div>
											{#if $runsStore.expandedRun.error.sql}
												<pre class="mt-1 whitespace-pre-wrap rounded bg-red-100/50 p-1.5 font-mono text-red-700">{$runsStore.expandedRun.error.sql}</pre>
											{/if}
										</div>
									{/if}

									{#if Object.keys($runsStore.expandedRun.parameters ?? {}).length > 0}
										<div class="mb-2">
											<span class="font-semibold text-gray-600">Parameters:</span>
											<pre class="mt-0.5 rounded bg-white p-1.5 text-gray-700">{JSON.stringify($runsStore.expandedRun.parameters, null, 2)}</pre>
										</div>
									{/if}

									<!-- Download buttons -->
									{#if run.status === 'success'}
										<div class="flex gap-2">
											<a
												href={downloadUrl(run.id, 'csv')}
												class="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-gray-200"
												download
											>
												Download CSV
											</a>
											<a
												href={downloadUrl(run.id, 'json')}
												class="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-gray-200"
												download
											>
												Download JSON
											</a>
										</div>
									{/if}
								</div>
							{/if}
						</div>
					{/each}
				</div>
			{/if}
		{/if}
	</div>
</div>

// frontend/src/components/ResultsPanel.tsx
import { useEffect, useMemo, useState } from 'react';
import { useResultsStore } from '@/stores/results';
import { useRunsStore } from '@/stores/runs';
import { useCteInspectionStore } from '@/stores/cteInspection';
import { useSourcePreviewStore } from '@/stores/sourcePreview';
import { api } from '@/api/client';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import DataViewer from './DataViewer';
import { ChevronDown, Loader2 } from 'lucide-react';

interface ResultsPanelProps {
  pipelineId: string;
  activeTab: string;
  onTabChange: (tab: string) => void;
}

export default function ResultsPanel({ pipelineId, activeTab, onTabChange }: ResultsPanelProps) {
  // Results
  const results = useResultsStore();

  // Runs
  const runs = useRunsStore((s) => s.runs);
  const runsLoading = useRunsStore((s) => s.loading);
  const expandedRun = useRunsStore((s) => s.expandedRun);
  const loadRuns = useRunsStore((s) => s.loadRuns);
  const loadRunDetail = useRunsStore((s) => s.loadRunDetail);

  // CTE inspection
  const cteState = useCteInspectionStore();

  // Source preview
  const sourcePreviewState = useSourcePreviewStore();

  const [expandedRunId, setExpandedRunId] = useState<string | null>(null);

  // Load data when switching tabs
  useEffect(() => {
    if (activeTab === 'history') {
      loadRuns(pipelineId);
    }
    if (activeTab === 'inputs' && !sourcePreviewState.cached && !sourcePreviewState.loading) {
      sourcePreviewState.loadSourcePreview(pipelineId);
    }
    if (activeTab === 'ctes' && results.runId !== cteState.cachedForRunId && !cteState.loading) {
      cteState.loadCteInspection(pipelineId, results.runId);
    }
  }, [activeTab]); // eslint-disable-line react-hooks/exhaustive-deps

  function toggleExpand(runId: string) {
    if (expandedRunId === runId) {
      setExpandedRunId(null);
    } else {
      setExpandedRunId(runId);
      loadRunDetail(pipelineId, runId);
    }
  }

  function formatTime(iso: string): string {
    return new Date(iso).toLocaleString();
  }

  function downloadUrl(runId: string, format: 'csv' | 'json'): string {
    return api.download.url(pipelineId, runId, format);
  }

  const selectedSourceData = useMemo(
    () => sourcePreviewState.sources.find((s) => s.name === sourcePreviewState.selectedSource) ?? null,
    [sourcePreviewState.sources, sourcePreviewState.selectedSource],
  );

  const selectedCteData = useMemo(
    () => cteState.ctes.find((c) => c.name === cteState.selectedCte) ?? null,
    [cteState.ctes, cteState.selectedCte],
  );

  return (
    <Tabs value={activeTab} onValueChange={onTabChange} className="flex h-full flex-col">
      <TabsList>
        <TabsTrigger value="inputs" data-testid="tab-inputs">Inputs</TabsTrigger>
        <TabsTrigger value="ctes" data-testid="tab-ctes">Intermediate CTEs</TabsTrigger>
        <TabsTrigger value="results" data-testid="tab-results">Results</TabsTrigger>
        <TabsTrigger value="history" data-testid="tab-history" className="ml-auto">Run History</TabsTrigger>
      </TabsList>

      {/* Inputs */}
      <TabsContent value="inputs">
        {sourcePreviewState.loading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Loading sources...
          </div>
        ) : sourcePreviewState.error ? (
          <div className="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{sourcePreviewState.error}</div>
        ) : sourcePreviewState.sources.length === 0 ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-400">No sources configured.</div>
        ) : (
          <>
            <div className="flex shrink-0 items-center gap-1.5 overflow-x-auto border-b border-gray-200 bg-white px-3 py-1.5">
              {sourcePreviewState.sources.map((src) => (
                <button
                  key={src.name}
                  className={`shrink-0 rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors ${
                    sourcePreviewState.selectedSource === src.name
                      ? 'bg-blue-100 text-blue-700'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  }`}
                  onClick={() => sourcePreviewState.selectSource(src.name)}
                >
                  {src.name}
                  <span className="ml-1 text-gray-400">{src.row_count}</span>
                </button>
              ))}
              {sourcePreviewState.durationMs != null && (
                <span className="ml-auto shrink-0 text-xs text-gray-400">{sourcePreviewState.durationMs}ms</span>
              )}
            </div>
            {selectedSourceData && (
              selectedSourceData.error ? (
                <div className="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{selectedSourceData.error}</div>
              ) : (
                <DataViewer key={sourcePreviewState.selectedSource} data={selectedSourceData.data} schema={selectedSourceData.schema_info} />
              )
            )}
          </>
        )}
      </TabsContent>

      {/* CTEs */}
      <TabsContent value="ctes">
        {cteState.loading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Inspecting CTEs...
          </div>
        ) : cteState.error ? (
          <div className="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{cteState.error}</div>
        ) : cteState.ctes.length === 0 ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-400">No CTEs found in the query.</div>
        ) : (
          <>
            <div className="flex shrink-0 items-center gap-1.5 overflow-x-auto border-b border-gray-200 bg-white px-3 py-1.5">
              {cteState.ctes.map((cte) => (
                <button
                  key={cte.name}
                  className={`shrink-0 rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors ${
                    cteState.selectedCte === cte.name
                      ? 'bg-blue-100 text-blue-700'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  }`}
                  onClick={() => cteState.selectCte(cte.name)}
                >
                  {cte.name}
                  <span className="ml-1 text-gray-400">{cte.row_count}</span>
                </button>
              ))}
              {cteState.durationMs != null && (
                <span className="ml-auto shrink-0 text-xs text-gray-400">{cteState.durationMs}ms</span>
              )}
            </div>
            {selectedCteData && (
              <DataViewer key={cteState.selectedCte} data={selectedCteData.data} schema={selectedCteData.schema_info} />
            )}
          </>
        )}
      </TabsContent>

      {/* Results */}
      <TabsContent value="results">
        {results.loading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Running query...
          </div>
        ) : results.error ? (
          <div className="m-3 rounded bg-red-50 p-3 text-sm text-red-600">{results.error}</div>
        ) : results.data.length === 0 ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-400">
            No results yet. Click Run to execute the pipeline.
          </div>
        ) : (
          <>
            <div className="flex shrink-0 items-center justify-between border-b border-gray-200 bg-white px-3 py-1">
              <span className="text-xs text-gray-500">
                Showing {results.data.length} of {results.rowCount ?? results.data.length} rows
                {results.durationMs != null && ` \u00b7 ${results.durationMs}ms`}
              </span>
              {results.runId && (
                <div className="flex gap-1.5" data-testid="download-buttons">
                  <a
                    href={downloadUrl(results.runId, 'csv')}
                    className="rounded bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-700 hover:bg-gray-200"
                    download
                  >
                    CSV
                  </a>
                  <a
                    href={downloadUrl(results.runId, 'json')}
                    className="rounded bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-700 hover:bg-gray-200"
                    download
                  >
                    JSON
                  </a>
                </div>
              )}
            </div>
            <DataViewer data={results.data} schema={results.schema} />
          </>
        )}
      </TabsContent>

      {/* Run History */}
      <TabsContent value="history" className="overflow-y-auto">
        {runsLoading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">Loading runs...</div>
        ) : runs.length === 0 ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-400">
            No runs yet. Click Run to execute the pipeline.
          </div>
        ) : (
          <div className="divide-y divide-gray-100">
            {runs.map((run) => (
              <div key={run.id}>
                <button
                  className="flex w-full items-center gap-3 px-3 py-2 text-left text-sm hover:bg-gray-50"
                  onClick={() => toggleExpand(run.id)}
                >
                  <span
                    className={`inline-block h-2 w-2 shrink-0 rounded-full ${
                      run.status === 'success' ? 'bg-green-500' : 'bg-red-500'
                    }`}
                  />
                  <span className="flex-1 text-gray-700">{formatTime(run.started_at)}</span>
                  <span className="text-xs text-gray-500">{run.duration_ms}ms</span>
                  {run.row_count != null && (
                    <span className="text-xs text-gray-500">{run.row_count} rows</span>
                  )}
                  <ChevronDown
                    className={`h-3.5 w-3.5 text-gray-400 transition-transform ${
                      expandedRunId === run.id ? 'rotate-180' : ''
                    }`}
                  />
                </button>

                {expandedRunId === run.id && expandedRun && (
                  <div className="border-t border-gray-100 bg-gray-50/50 px-4 py-3 text-xs">
                    {expandedRun.error && (
                      <div className="mb-2 space-y-1 rounded bg-red-50 p-2 text-red-600">
                        <div>{expandedRun.error.message}</div>
                        {expandedRun.error.sql && (
                          <pre className="mt-1 whitespace-pre-wrap rounded bg-red-100/50 p-1.5 font-mono text-red-700">
                            {expandedRun.error.sql}
                          </pre>
                        )}
                      </div>
                    )}

                    {Object.keys(expandedRun.parameters ?? {}).length > 0 && (
                      <div className="mb-2">
                        <span className="font-semibold text-gray-600">Parameters:</span>
                        <pre className="mt-0.5 rounded bg-white p-1.5 text-gray-700">
                          {JSON.stringify(expandedRun.parameters, null, 2)}
                        </pre>
                      </div>
                    )}

                    {run.status === 'success' && (
                      <div className="flex gap-2">
                        <a
                          href={downloadUrl(run.id, 'csv')}
                          className="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-gray-200"
                          download
                        >
                          Download CSV
                        </a>
                        <a
                          href={downloadUrl(run.id, 'json')}
                          className="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-gray-200"
                          download
                        >
                          Download JSON
                        </a>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </TabsContent>
    </Tabs>
  );
}
