// frontend/src/components/ApiSourceConfig.tsx
import { useCallback, useEffect, useState } from 'react';
import type { SourceRawResponse } from '@/types';
import { api } from '@/api/client';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { ChevronDown, ChevronRight, Loader2, Play } from 'lucide-react';
import KeyValueEditor from './KeyValueEditor';
import JsonTree from './JsonTree';

interface ApiSourceConfigProps {
  workflowId: string;
  sourceId: string;
  url: string;
  method: string;
  headers: { key: string; value: string }[];
  body: string;
  responsePath: string;
  savedUrl: string | undefined;
  onUrlChange: (url: string) => void;
  onMethodChange: (method: string) => void;
  onHeadersChange: (headers: { key: string; value: string }[]) => void;
  onBodyChange: (body: string) => void;
  onResponsePathChange: (path: string) => void;
  onFieldChange: () => void;
}

export default function ApiSourceConfig({
  workflowId,
  sourceId,
  url,
  method,
  headers,
  body,
  responsePath,
  savedUrl,
  onUrlChange,
  onMethodChange,
  onHeadersChange,
  onBodyChange,
  onResponsePathChange,
  onFieldChange,
}: ApiSourceConfigProps) {
  const [rawData, setRawData] = useState<SourceRawResponse | null>(null);
  const [rawLoading, setRawLoading] = useState(false);
  const [rawError, setRawError] = useState<string | null>(null);
  const [rawExpanded, setRawExpanded] = useState(false);

  // Clear raw preview when switching sources or when the saved URL changes
  useEffect(() => {
    setRawData(null);
    setRawError(null);
    setRawLoading(false);
    setRawExpanded(false);
  }, [sourceId, savedUrl]);

  const fetchRawPreview = useCallback(async () => {
    setRawLoading(true);
    setRawError(null);
    setRawData(null);
    setRawExpanded(true);
    try {
      const result = await api.sources.fetchRaw(workflowId, sourceId);
      setRawData(result);
    } catch (e) {
      setRawError(e instanceof Error ? e.message : 'Failed to fetch response');
    } finally {
      setRawLoading(false);
    }
  }, [workflowId, sourceId]);

  const handleSelectPath = useCallback(
    (path: string) => {
      onResponsePathChange(path);
      onFieldChange();
    },
    [onResponsePathChange, onFieldChange],
  );

  return (
    <>
      {/* URL */}
      <div>
        <div className="mb-1 flex items-center justify-between">
          <label className="block text-xs font-medium text-gray-600">URL</label>
          {url && (
            <button
              className="flex items-center gap-1 text-xs text-blue-600 underline hover:text-blue-800 disabled:opacity-50"
              onClick={fetchRawPreview}
              disabled={rawLoading}
            >
              {rawLoading ? (
                <>
                  <Loader2 className="h-3 w-3 animate-spin" />
                  Running...
                </>
              ) : (
                <>
                  <Play className="h-3 w-3" />
                  Run Request
                </>
              )}
            </button>
          )}
        </div>
        <Input
          className="text-sm"
          value={url}
          onChange={(e) => onUrlChange(e.target.value)}
          placeholder="https://api.example.com/data"
        />
      </div>

      <div className="w-28">
        <label className="mb-1 block text-xs font-medium text-gray-600">Method</label>
        <select
          className="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
          value={method}
          onChange={(e) => { onMethodChange(e.target.value); onFieldChange(); }}
        >
          <option value="GET">GET</option>
          <option value="POST">POST</option>
        </select>
      </div>

      <div>
        <label className="mb-1 block text-xs font-medium text-gray-600">Headers</label>
        <KeyValueEditor
          entries={headers}
          onChange={(newHeaders) => { onHeadersChange(newHeaders); onFieldChange(); }}
          keyPlaceholder="Header name"
          valuePlaceholder="Header value"
        />
      </div>

      {method === 'POST' && (
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">Body</label>
          <Textarea
            className="font-mono text-sm"
            rows={3}
            value={body}
            onChange={(e) => { onBodyChange(e.target.value); onFieldChange(); }}
            placeholder='{"key": "value"}'
          />
        </div>
      )}

      <div>
        <label className="mb-1 block text-xs font-medium text-gray-600">Response Path</label>
        <Input
          className="text-sm"
          value={responsePath}
          onChange={(e) => { onResponsePathChange(e.target.value); onFieldChange(); }}
          placeholder="data.results"
        />
      </div>

      {/* Raw response preview */}
      {(rawData || rawError) && (
        <div className="pt-1">
          <button
            className="flex items-center gap-1 text-xs font-medium text-gray-600 hover:text-gray-800"
            onClick={() => setRawExpanded(!rawExpanded)}
          >
            {rawExpanded ? (
              <ChevronDown className="h-3 w-3" />
            ) : (
              <ChevronRight className="h-3 w-3" />
            )}
            Raw Response
            {rawData && (
              <span className="ml-1 font-normal text-gray-400">(click arrays to set path)</span>
            )}
          </button>
          {rawExpanded && (
            <div className="mt-1 space-y-2">
              {rawError ? (
                <p className="text-xs text-red-600">{rawError}</p>
              ) : rawData ? (
                <div className="max-h-64 overflow-y-auto rounded border border-gray-200 bg-white p-2">
                  <JsonTree
                    data={rawData.raw_data}
                    selectedPath={responsePath || undefined}
                    onSelectPath={handleSelectPath}
                  />
                </div>
              ) : null}
            </div>
          )}
        </div>
      )}
    </>
  );
}

// frontend/src/lib/components/panel/config/ApiSourceConfig.svelte
<script lang="ts">
	import { updateNodeConfig } from '$lib/stores/pipeline.js';
	import { runPreview } from '$lib/stores/preview.js';
	import { debounce } from '$lib/utils/debounce.js';
	import KeyValueEditor from './KeyValueEditor.svelte';

	let {
		pipelineId,
		nodeId,
		config,
		outputTableName
	}: {
		pipelineId: string;
		nodeId: string;
		config: Record<string, unknown>;
		outputTableName: string;
	} = $props();

	let url = $state((config.url as string) ?? '');
	let method = $state((config.method as string) ?? 'GET');
	let headers = $state<{ key: string; value: string }[]>(
		Array.isArray(config.headers)
			? (config.headers as { key: string; value: string }[])
			: []
	);
	let body = $state((config.body as string) ?? '');
	let responsePath = $state((config.response_path as string) ?? '');
	let tableName = $state(outputTableName);

	const saveConfig = debounce(() => {
		updateNodeConfig(pipelineId, nodeId, {
			config: {
				url,
				method,
				headers: headers.filter((h) => h.key),
				body: method === 'POST' ? body : undefined,
				response_path: responsePath || undefined
			},
			output_table_name: tableName || undefined
		});
	}, 500);

	function onchange() {
		saveConfig();
	}

	function testConnection() {
		saveConfig.cancel();
		updateNodeConfig(pipelineId, nodeId, {
			config: {
				url,
				method,
				headers: headers.filter((h) => h.key),
				body: method === 'POST' ? body : undefined,
				response_path: responsePath || undefined
			},
			output_table_name: tableName || undefined
		}).then(() => {
			runPreview(pipelineId, nodeId);
		});
	}
</script>

<div class="space-y-3 p-3">
	<div>
		<label class="mb-1 block text-xs font-medium text-gray-600">URL</label>
		<input
			class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
			bind:value={url}
			oninput={onchange}
			placeholder="https://api.example.com/data"
		/>
	</div>

	<div class="flex gap-3">
		<div class="w-28">
			<label class="mb-1 block text-xs font-medium text-gray-600">Method</label>
			<select
				class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
				bind:value={method}
				onchange={onchange}
			>
				<option value="GET">GET</option>
				<option value="POST">POST</option>
			</select>
		</div>

		<div class="flex-1">
			<label class="mb-1 block text-xs font-medium text-gray-600">Output Table</label>
			<input
				class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
				bind:value={tableName}
				oninput={onchange}
				placeholder="api_data"
			/>
		</div>
	</div>

	<div>
		<label class="mb-1 block text-xs font-medium text-gray-600">Headers</label>
		<KeyValueEditor bind:entries={headers} keyPlaceholder="Header name" valuePlaceholder="Header value" />
	</div>

	{#if method === 'POST'}
		<div>
			<label class="mb-1 block text-xs font-medium text-gray-600">Body</label>
			<textarea
				class="w-full rounded border border-gray-300 px-2 py-1.5 font-mono text-sm focus:border-blue-500 focus:outline-none"
				rows="3"
				bind:value={body}
				oninput={onchange}
				placeholder={'{"key": "value"}'}
			></textarea>
		</div>
	{/if}

	<div>
		<label class="mb-1 block text-xs font-medium text-gray-600">Response Path (JSONPath)</label>
		<input
			class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
			bind:value={responsePath}
			oninput={onchange}
			placeholder="$.data"
		/>
	</div>

	<button
		class="rounded bg-blue-50 px-3 py-1.5 text-xs font-medium text-blue-600 hover:bg-blue-100"
		onclick={testConnection}
	>
		Test Connection
	</button>
</div>
