// frontend/src/components/FileSourceConfig.tsx
import { useState } from 'react';
import { api } from '@/api/client';
import { addToast } from '@/stores/toasts';
import { deriveTableName } from '@/utils/tableName';
import { Input } from '@/components/ui/input';

interface FileSourceConfigProps {
  workflowId: string;
  sourceId: string;
  filename: string;
  fileType: string;
  delimiter: string;
  hasHeader: boolean;
  otherTableNames: string[];
  tableNameManuallyEdited: boolean;
  onFilenameChange: (filename: string) => void;
  onFileTypeChange: (fileType: string) => void;
  onDelimiterChange: (delimiter: string) => void;
  onHasHeaderChange: (hasHeader: boolean) => void;
  onTableNameDerived: (tableName: string) => void;
  onFieldChange: () => void;
  onUploadComplete: () => void;
}

export default function FileSourceConfig({
  workflowId,
  sourceId,
  filename,
  fileType,
  delimiter,
  hasHeader,
  otherTableNames,
  tableNameManuallyEdited,
  onFilenameChange,
  onFileTypeChange,
  onDelimiterChange,
  onHasHeaderChange,
  onTableNameDerived,
  onFieldChange,
  onUploadComplete,
}: FileSourceConfigProps) {
  const [uploading, setUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);

  async function handleFile(file: File) {
    setUploading(true);
    try {
      const result = await api.files.upload(workflowId, file);
      onFilenameChange(result.filename);
      onFileTypeChange(result.file_type);

      if (!tableNameManuallyEdited) {
        onTableNameDerived(deriveTableName(result.filename, otherTableNames));
      }

      onUploadComplete();
      addToast(`Uploaded ${result.filename}`, 'success');
    } catch (e) {
      addToast(`Upload failed: ${e instanceof Error ? e.message : String(e)}`, 'error');
    } finally {
      setUploading(false);
    }
  }

  function onFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    if (e.target.files?.[0]) handleFile(e.target.files[0]);
  }

  function onDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer?.files?.[0]) handleFile(e.dataTransfer.files[0]);
  }

  return (
    <>
      {/* File upload */}
      <div
        className={`relative rounded-lg border-2 border-dashed p-3 text-center transition-colors ${
          dragOver ? 'border-green-400 bg-green-50' : 'border-gray-300 hover:border-gray-400'
        }`}
        onDrop={onDrop}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
      >
        {uploading ? (
          <p className="text-sm text-gray-500">Uploading...</p>
        ) : filename ? (
          <>
            <p className="text-sm font-medium text-gray-700">{filename}</p>
            <p className="text-xs text-gray-400">Drop a new file to replace</p>
          </>
        ) : (
          <p className="text-sm text-gray-500">Drop a file here or click to browse</p>
        )}
        <input
          type="file"
          className="absolute inset-0 cursor-pointer opacity-0"
          onChange={onFileInput}
          accept=".csv,.tsv,.json,.xlsx,.xls,.parquet"
        />
      </div>

      {fileType === 'csv' && (
        <div className="flex gap-3">
          <div className="w-20">
            <label className="mb-1 block text-xs font-medium text-gray-600">Delimiter</label>
            <Input
              className="text-sm"
              value={delimiter}
              onChange={(e) => { onDelimiterChange(e.target.value); onFieldChange(); }}
            />
          </div>
          <div className="flex items-end gap-1.5 pb-0.5">
            <input
              type="checkbox"
              id={`header-${sourceId}`}
              checked={hasHeader}
              onChange={(e) => { onHasHeaderChange(e.target.checked); onFieldChange(); }}
            />
            <label htmlFor={`header-${sourceId}`} className="text-xs text-gray-600">Header row</label>
          </div>
        </div>
      )}
    </>
  );
}

// frontend/src/lib/components/panel/config/FileSourceConfig.svelte
<script lang="ts">
	import { updateNodeConfig } from '$lib/stores/pipeline.js';
	import { api } from '$lib/api/client.js';
	import { addToast } from '$lib/stores/toasts.js';
	import { debounce } from '$lib/utils/debounce.js';

	let {
		pipelineId,
		nodeId,
		config,
		outputTableName
	}: {
		pipelineId: string;
		nodeId: string;
		config: Record<string, unknown>;
		outputTableName: string;
	} = $props();

	let filename = $state((config.filename as string) ?? '');
	let fileType = $state((config.file_type as string) ?? '');
	let delimiter = $state((config.delimiter as string) ?? ',');
	let hasHeader = $state((config.has_header as boolean) ?? true);
	let encoding = $state((config.encoding as string) ?? 'utf-8');
	let sheet = $state((config.sheet as string) ?? '');
	let tableName = $state(outputTableName);
	let uploading = $state(false);
	let dragOver = $state(false);

	const saveConfig = debounce(() => {
		const cfg: Record<string, unknown> = { filename, file_type: fileType };
		if (fileType === 'csv') {
			cfg.delimiter = delimiter;
			cfg.has_header = hasHeader;
			cfg.encoding = encoding;
		} else if (fileType === 'excel') {
			cfg.sheet = sheet || undefined;
		}
		updateNodeConfig(pipelineId, nodeId, {
			config: cfg,
			output_table_name: tableName || undefined
		});
	}, 500);

	async function handleFile(file: File) {
		uploading = true;
		try {
			const result = await api.files.upload(pipelineId, file);
			filename = result.filename;
			fileType = result.file_type;
			saveConfig.cancel();
			saveConfig();
			addToast(`Uploaded ${result.filename}`, 'success');
		} catch (e) {
			addToast(`Upload failed: ${e instanceof Error ? e.message : String(e)}`, 'error');
		} finally {
			uploading = false;
		}
	}

	function onFileInput(e: Event) {
		const input = e.target as HTMLInputElement;
		if (input.files?.[0]) handleFile(input.files[0]);
	}

	function onDrop(e: DragEvent) {
		e.preventDefault();
		dragOver = false;
		if (e.dataTransfer?.files?.[0]) handleFile(e.dataTransfer.files[0]);
	}

	function onDragOver(e: DragEvent) {
		e.preventDefault();
		dragOver = true;
	}

	function onDragLeave() {
		dragOver = false;
	}

	function onchange() {
		saveConfig();
	}
</script>

<div class="space-y-3 p-3">
	<!-- Drop zone -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="rounded-lg border-2 border-dashed p-4 text-center transition-colors {dragOver
			? 'border-green-400 bg-green-50'
			: 'border-gray-300 hover:border-gray-400'}"
		ondrop={onDrop}
		ondragover={onDragOver}
		ondragleave={onDragLeave}
	>
		{#if uploading}
			<p class="text-sm text-gray-500">Uploading...</p>
		{:else if filename}
			<p class="text-sm font-medium text-gray-700">{filename}</p>
			<p class="text-xs text-gray-400">Drop a new file to replace</p>
		{:else}
			<p class="text-sm text-gray-500">Drop a file here or click to browse</p>
		{/if}
		<input
			type="file"
			class="absolute inset-0 cursor-pointer opacity-0"
			onchange={onFileInput}
			accept=".csv,.tsv,.json,.xlsx,.xls,.parquet"
			style="position: relative;"
		/>
	</div>

	<div>
		<label class="mb-1 block text-xs font-medium text-gray-600">Output Table</label>
		<input
			class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
			bind:value={tableName}
			oninput={onchange}
			placeholder="file_data"
		/>
	</div>

	{#if fileType === 'csv'}
		<div class="flex gap-3">
			<div class="w-20">
				<label class="mb-1 block text-xs font-medium text-gray-600">Delimiter</label>
				<input
					class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
					bind:value={delimiter}
					oninput={onchange}
				/>
			</div>
			<div class="w-24">
				<label class="mb-1 block text-xs font-medium text-gray-600">Encoding</label>
				<input
					class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
					bind:value={encoding}
					oninput={onchange}
				/>
			</div>
			<div class="flex items-end gap-1.5 pb-0.5">
				<input type="checkbox" id="header-{nodeId}" bind:checked={hasHeader} onchange={onchange} />
				<label for="header-{nodeId}" class="text-xs text-gray-600">Header row</label>
			</div>
		</div>
	{/if}

	{#if fileType === 'excel'}
		<div>
			<label class="mb-1 block text-xs font-medium text-gray-600">Sheet name</label>
			<input
				class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
				bind:value={sheet}
				oninput={onchange}
				placeholder="Sheet1"
			/>
		</div>
	{/if}
</div>
