// frontend/src/components/ParameterModal.tsx
import { useState } from 'react';
import type { PipelineParameter } from '@/types';
import { usePipelineStore } from '@/stores/pipeline';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { X } from 'lucide-react';

interface ParameterModalProps {
  pipelineId: string;
  parameters: PipelineParameter[];
  open: boolean;
  onClose: () => void;
}

export default function ParameterModal({ pipelineId, parameters, open, onClose }: ParameterModalProps) {
  const updatePipelineParams = usePipelineStore((s) => s.updatePipelineParams);
  const [rows, setRows] = useState<PipelineParameter[]>(
    parameters.length > 0 ? parameters.map((p) => ({ ...p })) : [],
  );
  const [nameError, setNameError] = useState('');

  function addRow() {
    setRows([...rows, { name: '', type: 'string', default: '', description: '' }]);
  }

  function removeRow(index: number) {
    setRows(rows.filter((_, i) => i !== index));
  }

  function updateRow(index: number, field: keyof PipelineParameter, value: string) {
    setRows(rows.map((r, i) => (i === index ? { ...r, [field]: value } : r)));
  }

  function validate(): boolean {
    const names = rows.map((r) => r.name.trim()).filter(Boolean);
    const identifierRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
    for (const name of names) {
      if (!identifierRegex.test(name)) {
        setNameError(`Invalid name: "${name}" (must be a valid identifier)`);
        return false;
      }
    }
    if (new Set(names).size !== names.length) {
      setNameError('Duplicate parameter names');
      return false;
    }
    setNameError('');
    return true;
  }

  async function save() {
    if (!validate()) return;
    const cleaned = rows
      .filter((r) => r.name.trim())
      .map((r) => ({
        name: r.name.trim(),
        type: r.type,
        default: r.default || null,
        description: r.description || null,
      }));
    await updatePipelineParams(pipelineId, cleaned);
    onClose();
  }

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-xl" data-testid="parameter-modal">
        <DialogHeader>
          <DialogTitle>Pipeline Parameters</DialogTitle>
          <DialogDescription>Define parameters that can be provided at runtime.</DialogDescription>
        </DialogHeader>

        {nameError && (
          <div className="rounded bg-red-50 p-2 text-sm text-red-600">{nameError}</div>
        )}

        <div className="max-h-80 space-y-2 overflow-y-auto">
          {rows.map((row, i) => (
            <div key={i} className="flex items-start gap-2 rounded border border-gray-200 p-2">
              <div className="flex-1">
                <Input
                  className="mb-1"
                  placeholder="Name"
                  value={row.name}
                  onChange={(e) => updateRow(i, 'name', e.target.value)}
                />
                <div className="flex gap-1">
                  <select
                    className="w-24 rounded border border-gray-300 px-1 py-1 text-xs focus:border-blue-500 focus:outline-none"
                    value={row.type}
                    onChange={(e) => updateRow(i, 'type', e.target.value)}
                  >
                    <option value="string">string</option>
                    <option value="number">number</option>
                    <option value="boolean">boolean</option>
                  </select>
                  <Input
                    className="flex-1 text-xs"
                    placeholder="Default value"
                    value={row.default ?? ''}
                    onChange={(e) => updateRow(i, 'default', e.target.value)}
                  />
                </div>
                <Input
                  className="mt-1 text-xs"
                  placeholder="Description"
                  value={row.description ?? ''}
                  onChange={(e) => updateRow(i, 'description', e.target.value)}
                />
              </div>
              <button
                className="mt-1 text-gray-400 hover:text-red-500"
                onClick={() => removeRow(i)}
                aria-label="Remove parameter"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>

        <button className="text-sm text-blue-600 hover:text-blue-700" onClick={addRow}>
          + Add Parameter
        </button>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={save}>Save</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/lib/components/ParameterModal.svelte
<script lang="ts">
	import type { PipelineParameter } from '$lib/types/index.js';
	import { updatePipelineParams } from '$lib/stores/pipeline.js';

	let {
		pipelineId,
		parameters,
		onClose
	}: {
		pipelineId: string;
		parameters: PipelineParameter[];
		onClose: () => void;
	} = $props();

	let rows = $state<PipelineParameter[]>(
		parameters.length > 0
			? parameters.map((p) => ({ ...p }))
			: []
	);

	let nameError = $state('');

	function addRow() {
		rows = [...rows, { name: '', type: 'string', default: '', description: '' }];
	}

	function removeRow(index: number) {
		rows = rows.filter((_, i) => i !== index);
	}

	function validate(): boolean {
		const names = rows.map((r) => r.name.trim()).filter(Boolean);
		const identifierRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
		for (const name of names) {
			if (!identifierRegex.test(name)) {
				nameError = `Invalid name: "${name}" (must be a valid identifier)`;
				return false;
			}
		}
		if (new Set(names).size !== names.length) {
			nameError = 'Duplicate parameter names';
			return false;
		}
		nameError = '';
		return true;
	}

	async function save() {
		if (!validate()) return;
		const cleaned = rows
			.filter((r) => r.name.trim())
			.map((r) => ({
				name: r.name.trim(),
				type: r.type,
				default: r.default || null,
				description: r.description || null
			}));
		await updatePipelineParams(pipelineId, cleaned);
		onClose();
	}

	function onBackdropClick(e: MouseEvent) {
		if (e.target === e.currentTarget) onClose();
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
	class="fixed inset-0 z-50 flex items-center justify-center bg-black/40"
	onclick={onBackdropClick}
>
	<div class="w-full max-w-xl rounded-lg bg-white p-5 shadow-xl" data-testid="parameter-modal">
		<h2 class="mb-4 text-lg font-semibold text-gray-800">Pipeline Parameters</h2>

		{#if nameError}
			<div class="mb-3 rounded bg-red-50 p-2 text-sm text-red-600">{nameError}</div>
		{/if}

		<div class="max-h-80 space-y-2 overflow-y-auto">
			{#each rows as row, i}
				<div class="flex items-start gap-2 rounded border border-gray-200 p-2">
					<div class="flex-1">
						<input
							class="mb-1 w-full rounded border border-gray-300 px-2 py-1 text-sm focus:border-blue-500 focus:outline-none"
							placeholder="Name"
							bind:value={row.name}
						/>
						<div class="flex gap-1">
							<select
								class="w-24 rounded border border-gray-300 px-1 py-1 text-xs focus:border-blue-500 focus:outline-none"
								bind:value={row.type}
							>
								<option value="string">string</option>
								<option value="number">number</option>
								<option value="boolean">boolean</option>
							</select>
							<input
								class="flex-1 rounded border border-gray-300 px-2 py-1 text-xs focus:border-blue-500 focus:outline-none"
								placeholder="Default value"
								bind:value={row.default}
							/>
						</div>
						<input
							class="mt-1 w-full rounded border border-gray-300 px-2 py-1 text-xs focus:border-blue-500 focus:outline-none"
							placeholder="Description"
							bind:value={row.description}
						/>
					</div>
					<button
						class="mt-1 text-gray-400 hover:text-red-500"
						onclick={() => removeRow(i)}
						aria-label="Remove parameter"
					>
						<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
							<line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
						</svg>
					</button>
				</div>
			{/each}
		</div>

		<button class="mt-2 text-sm text-blue-600 hover:text-blue-700" onclick={addRow}>
			+ Add Parameter
		</button>

		<div class="mt-4 flex justify-end gap-2">
			<button
				class="rounded border border-gray-300 px-4 py-1.5 text-sm text-gray-700 hover:bg-gray-50"
				onclick={onClose}
			>
				Cancel
			</button>
			<button
				class="rounded bg-blue-600 px-4 py-1.5 text-sm font-medium text-white hover:bg-blue-700"
				onclick={save}
			>
				Save
			</button>
		</div>
	</div>
</div>
