// frontend/src/components/SourceConfigPanel.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { SourceResponse, SchemaColumn } from '@/types';
import { usePipelineStore } from '@/stores/pipeline';
import { api } from '@/api/client';
import { addToast } from '@/stores/toasts';
import { debounce } from '@/utils/debounce';
import { deriveTableName, tableNameFromUrl } from '@/utils/tableName';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import KeyValueEditor from './KeyValueEditor';

interface SourceConfigPanelProps {
  pipelineId: string;
  source: SourceResponse;
}

export default function SourceConfigPanel({ pipelineId, source }: SourceConfigPanelProps) {
  const updateSource = usePipelineStore((s) => s.updateSource);
  const pipeline = usePipelineStore((s) => s.pipeline);

  // ── File source state ──
  const [filename, setFilename] = useState((source.config.filename as string) ?? '');
  const [fileType, setFileType] = useState((source.config.file_type as string) ?? '');
  const [delimiter, setDelimiter] = useState((source.config.delimiter as string) ?? ',');
  const [hasHeader, setHasHeader] = useState((source.config.has_header as boolean) ?? true);
  const [uploading, setUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);

  // ── API source state ──
  const [url, setUrl] = useState((source.config.url as string) ?? '');
  const [method, setMethod] = useState((source.config.method as string) ?? 'GET');
  const [headers, setHeaders] = useState<{ key: string; value: string }[]>(
    Array.isArray(source.config.headers)
      ? (source.config.headers as { key: string; value: string }[])
      : [],
  );
  const [body, setBody] = useState((source.config.body as string) ?? '');
  const [responsePath, setResponsePath] = useState((source.config.response_path as string) ?? '');

  // ── Common ──
  const [tableName, setTableName] = useState(source.table_name);
  const [tableNameManuallyEdited, setTableNameManuallyEdited] = useState(false);

  // ── Schema state ──
  const [schemaColumns, setSchemaColumns] = useState<SchemaColumn[]>([]);
  const [schemaRowCount, setSchemaRowCount] = useState<number | null>(null);
  const [schemaLoading, setSchemaLoading] = useState(false);
  const [schemaError, setSchemaError] = useState<string | null>(null);

  const otherTableNames = useMemo(
    () => (pipeline?.sources ?? []).filter((s) => s.id !== source.id).map((s) => s.table_name),
    [pipeline?.sources, source.id],
  );

  const sourceConfigured = source.type === 'file'
    ? !!(source.config.filename as string)
    : !!(source.config.url as string);

  // Reset state when source changes
  useEffect(() => {
    setTableName(source.table_name);
    setFilename((source.config.filename as string) ?? '');
    setFileType((source.config.file_type as string) ?? '');
    setDelimiter((source.config.delimiter as string) ?? ',');
    setHasHeader((source.config.has_header as boolean) ?? true);
    setUrl((source.config.url as string) ?? '');
    setMethod((source.config.method as string) ?? 'GET');
    setHeaders(
      Array.isArray(source.config.headers)
        ? (source.config.headers as { key: string; value: string }[])
        : [],
    );
    setBody((source.config.body as string) ?? '');
    setResponsePath((source.config.response_path as string) ?? '');
    setTableNameManuallyEdited(false);
  }, [source]);

  const fetchSchema = useCallback(async () => {
    setSchemaLoading(true);
    setSchemaError(null);
    try {
      const result = await api.sources.schema(pipelineId, source.id);
      setSchemaColumns(result.columns);
      setSchemaRowCount(result.row_count);
    } catch (e) {
      setSchemaError(e instanceof Error ? e.message : 'Failed to load schema');
      setSchemaColumns([]);
      setSchemaRowCount(null);
    } finally {
      setSchemaLoading(false);
    }
  }, [pipelineId, source.id]);

  // Auto-fetch schema when source is configured
  useEffect(() => {
    if (sourceConfigured) {
      fetchSchema();
    } else {
      setSchemaColumns([]);
      setSchemaRowCount(null);
      setSchemaError(null);
    }
  }, [source.id, sourceConfigured, fetchSchema]);

  // Use a ref to hold the latest local state for the debounced save
  const stateRef = useRef({ tableName, filename, fileType, delimiter, hasHeader, url, method, headers, body, responsePath });
  stateRef.current = { tableName, filename, fileType, delimiter, hasHeader, url, method, headers, body, responsePath };

  const saveConfig = useMemo(
    () =>
      debounce(() => {
        const s = stateRef.current;
        const config = source.type === 'file'
          ? (() => {
              const cfg: Record<string, unknown> = { filename: s.filename, file_type: s.fileType };
              if (s.fileType === 'csv') {
                cfg.delimiter = s.delimiter;
                cfg.has_header = s.hasHeader;
              }
              return cfg;
            })()
          : {
              url: s.url,
              method: s.method,
              headers: s.headers.filter((h) => h.key),
              body: s.method === 'POST' ? s.body : undefined,
              response_path: s.responsePath || undefined,
            };
        updateSource(pipelineId, source.id, {
          table_name: s.tableName || undefined,
          config,
        });
      }, 500),
    [pipelineId, source.id, source.type, updateSource],
  );

  function onFieldChange() {
    saveConfig();
  }

  function onTableNameInput(val: string) {
    setTableName(val);
    setTableNameManuallyEdited(true);
    saveConfig();
  }

  function onUrlInput(val: string) {
    setUrl(val);
    if (!tableNameManuallyEdited) {
      const segment = tableNameFromUrl(val);
      if (segment) {
        setTableName(deriveTableName(segment, otherTableNames));
      }
    }
    saveConfig();
  }

  async function handleFile(file: File) {
    setUploading(true);
    try {
      const result = await api.files.upload(pipelineId, file);
      setFilename(result.filename);
      setFileType(result.file_type);

      if (!tableNameManuallyEdited) {
        setTableName(deriveTableName(result.filename, otherTableNames));
      }

      saveConfig.cancel();
      saveConfig();
      setTimeout(() => fetchSchema(), 600);
      addToast(`Uploaded ${result.filename}`, 'success');
    } catch (e) {
      addToast(`Upload failed: ${e instanceof Error ? e.message : String(e)}`, 'error');
    } finally {
      setUploading(false);
    }
  }

  function onFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    if (e.target.files?.[0]) handleFile(e.target.files[0]);
  }

  function onDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer?.files?.[0]) handleFile(e.dataTransfer.files[0]);
  }

  return (
    <div className="border-t border-gray-200 bg-gray-50/50" data-testid="source-config">
      <div className="space-y-3 p-3">
        {/* Table name */}
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">Table Name</label>
          <Input
            className="text-sm"
            value={tableName}
            onChange={(e) => onTableNameInput(e.target.value)}
            placeholder="my_table"
          />
        </div>

        {source.type === 'file' ? (
          <>
            {/* File upload */}
            <div
              className={`relative rounded-lg border-2 border-dashed p-3 text-center transition-colors ${
                dragOver ? 'border-green-400 bg-green-50' : 'border-gray-300 hover:border-gray-400'
              }`}
              onDrop={onDrop}
              onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
              onDragLeave={() => setDragOver(false)}
            >
              {uploading ? (
                <p className="text-sm text-gray-500">Uploading...</p>
              ) : filename ? (
                <>
                  <p className="text-sm font-medium text-gray-700">{filename}</p>
                  <p className="text-xs text-gray-400">Drop a new file to replace</p>
                </>
              ) : (
                <p className="text-sm text-gray-500">Drop a file here or click to browse</p>
              )}
              <input
                type="file"
                className="absolute inset-0 cursor-pointer opacity-0"
                onChange={onFileInput}
                accept=".csv,.tsv,.json,.xlsx,.xls,.parquet"
              />
            </div>

            {fileType === 'csv' && (
              <div className="flex gap-3">
                <div className="w-20">
                  <label className="mb-1 block text-xs font-medium text-gray-600">Delimiter</label>
                  <Input
                    className="text-sm"
                    value={delimiter}
                    onChange={(e) => { setDelimiter(e.target.value); onFieldChange(); }}
                  />
                </div>
                <div className="flex items-end gap-1.5 pb-0.5">
                  <input
                    type="checkbox"
                    id={`header-${source.id}`}
                    checked={hasHeader}
                    onChange={(e) => { setHasHeader(e.target.checked); onFieldChange(); }}
                  />
                  <label htmlFor={`header-${source.id}`} className="text-xs text-gray-600">Header row</label>
                </div>
              </div>
            )}
          </>
        ) : (
          <>
            {/* API source */}
            <div>
              <label className="mb-1 block text-xs font-medium text-gray-600">URL</label>
              <Input
                className="text-sm"
                value={url}
                onChange={(e) => onUrlInput(e.target.value)}
                placeholder="https://api.example.com/data"
              />
            </div>

            <div className="w-28">
              <label className="mb-1 block text-xs font-medium text-gray-600">Method</label>
              <select
                className="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
                value={method}
                onChange={(e) => { setMethod(e.target.value); onFieldChange(); }}
              >
                <option value="GET">GET</option>
                <option value="POST">POST</option>
              </select>
            </div>

            <div>
              <label className="mb-1 block text-xs font-medium text-gray-600">Headers</label>
              <KeyValueEditor
                entries={headers}
                onChange={(newHeaders) => { setHeaders(newHeaders); onFieldChange(); }}
                keyPlaceholder="Header name"
                valuePlaceholder="Header value"
              />
            </div>

            {method === 'POST' && (
              <div>
                <label className="mb-1 block text-xs font-medium text-gray-600">Body</label>
                <Textarea
                  className="font-mono text-sm"
                  rows={3}
                  value={body}
                  onChange={(e) => { setBody(e.target.value); onFieldChange(); }}
                  placeholder='{"key": "value"}'
                />
              </div>
            )}

            <div>
              <label className="mb-1 block text-xs font-medium text-gray-600">Response Path</label>
              <Input
                className="text-sm"
                value={responsePath}
                onChange={(e) => { setResponsePath(e.target.value); onFieldChange(); }}
                placeholder="data.results"
              />
            </div>
          </>
        )}

        {/* Schema display */}
        {schemaLoading ? (
          <div className="pt-1">
            <p className="text-xs text-gray-400">Loading schema...</p>
          </div>
        ) : schemaError ? (
          <div className="pt-1">
            <p className="text-xs text-red-400">{schemaError}</p>
          </div>
        ) : schemaColumns.length > 0 ? (
          <div className="pt-1">
            <div className="mb-1 flex items-center justify-between">
              <span className="text-xs font-medium text-gray-600">Schema</span>
              {schemaRowCount !== null && (
                <span className="text-xs text-gray-400">{schemaRowCount.toLocaleString()} rows</span>
              )}
            </div>
            <div className="max-h-48 overflow-y-auto rounded border border-gray-200 bg-white">
              <table className="w-full text-xs">
                <tbody>
                  {schemaColumns.map((col, i) => (
                    <tr key={col.name} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                      <td className="px-2 py-1 font-medium text-gray-700">{col.name}</td>
                      <td className="px-2 py-1 text-right font-mono text-gray-400">{col.type}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}

// frontend/src/lib/components/SourceConfigPanel.svelte
<script lang="ts">
	import type { SourceResponse, SchemaColumn } from '$lib/types/index.js';
	import { updateSource, pipelineStore } from '$lib/stores/pipeline.js';
	import { api } from '$lib/api/client.js';
	import { addToast } from '$lib/stores/toasts.js';
	import { debounce } from '$lib/utils/debounce.js';
	import { deriveTableName, tableNameFromUrl } from '$lib/utils/tableName.js';
	import KeyValueEditor from '$lib/components/panel/config/KeyValueEditor.svelte';

	let {
		pipelineId,
		source,
	}: {
		pipelineId: string;
		source: SourceResponse;
	} = $props();

	// ── File source state ──
	// svelte-ignore state_referenced_locally
	let filename = $state((source.config.filename as string) ?? '');
	// svelte-ignore state_referenced_locally
	let fileType = $state((source.config.file_type as string) ?? '');
	// svelte-ignore state_referenced_locally
	let delimiter = $state((source.config.delimiter as string) ?? ',');
	// svelte-ignore state_referenced_locally
	let hasHeader = $state((source.config.has_header as boolean) ?? true);
	let uploading = $state(false);
	let dragOver = $state(false);

	// ── API source state ──
	// svelte-ignore state_referenced_locally
	let url = $state((source.config.url as string) ?? '');
	// svelte-ignore state_referenced_locally
	let method = $state((source.config.method as string) ?? 'GET');
	// svelte-ignore state_referenced_locally
	let headers = $state<{ key: string; value: string }[]>(
		// svelte-ignore state_referenced_locally
		Array.isArray(source.config.headers)
			? (source.config.headers as { key: string; value: string }[])
			: []
	);
	// svelte-ignore state_referenced_locally
	let body = $state((source.config.body as string) ?? '');
	// svelte-ignore state_referenced_locally
	let responsePath = $state((source.config.response_path as string) ?? '');

	// ── Common ──
	// svelte-ignore state_referenced_locally
	let tableName = $state(source.table_name);

	/** Table names of other sources in this pipeline (for dedup). */
	let otherTableNames = $derived(
		($pipelineStore.pipeline?.sources ?? [])
			.filter((s) => s.id !== source.id)
			.map((s) => s.table_name)
	);

	/** Whether the user has manually edited the table name. */
	let tableNameManuallyEdited = $state(false);

	// ── Schema state ──
	let schemaColumns = $state<SchemaColumn[]>([]);
	let schemaRowCount = $state<number | null>(null);
	let schemaLoading = $state(false);
	let schemaError = $state<string | null>(null);

	/** Whether this source has enough config to fetch schema. */
	let sourceConfigured = $derived(
		source.type === 'file'
			? !!(source.config.filename as string)
			: !!(source.config.url as string)
	);

	async function fetchSchema() {
		schemaLoading = true;
		schemaError = null;
		try {
			const result = await api.sources.schema(pipelineId, source.id);
			schemaColumns = result.columns;
			schemaRowCount = result.row_count;
		} catch (e) {
			schemaError = e instanceof Error ? e.message : 'Failed to load schema';
			schemaColumns = [];
			schemaRowCount = null;
		} finally {
			schemaLoading = false;
		}
	}

	// Auto-fetch schema when source is configured (and when source identity changes)
	$effect(() => {
		// Read source.id and sourceConfigured to establish reactivity
		const _id = source.id;
		const _configured = sourceConfigured;
		if (_configured) {
			fetchSchema();
		} else {
			schemaColumns = [];
			schemaRowCount = null;
			schemaError = null;
		}
	});

	// Reset state when source changes
	$effect(() => {
		tableName = source.table_name;
		filename = (source.config.filename as string) ?? '';
		fileType = (source.config.file_type as string) ?? '';
		delimiter = (source.config.delimiter as string) ?? ',';
		hasHeader = (source.config.has_header as boolean) ?? true;
		url = (source.config.url as string) ?? '';
		method = (source.config.method as string) ?? 'GET';
		headers = Array.isArray(source.config.headers)
			? (source.config.headers as { key: string; value: string }[])
			: [];
		body = (source.config.body as string) ?? '';
		responsePath = (source.config.response_path as string) ?? '';
	});

	function buildFileConfig(): Record<string, unknown> {
		const cfg: Record<string, unknown> = { filename, file_type: fileType };
		if (fileType === 'csv') {
			cfg.delimiter = delimiter;
			cfg.has_header = hasHeader;
		}
		return cfg;
	}

	function buildApiConfig(): Record<string, unknown> {
		return {
			url,
			method,
			headers: headers.filter((h) => h.key),
			body: method === 'POST' ? body : undefined,
			response_path: responsePath || undefined,
		};
	}

	const saveConfig = debounce(() => {
		const config = source.type === 'file' ? buildFileConfig() : buildApiConfig();
		updateSource(pipelineId, source.id, {
			table_name: tableName || undefined,
			config,
		});
	}, 500);

	function onchange() {
		saveConfig();
	}

	function onTableNameInput() {
		tableNameManuallyEdited = true;
		saveConfig();
	}

	function onUrlInput() {
		// Auto-derive table name from URL (unless user manually edited it)
		if (!tableNameManuallyEdited) {
			const segment = tableNameFromUrl(url);
			if (segment) {
				tableName = deriveTableName(segment, otherTableNames);
			}
		}
		saveConfig();
	}

	async function handleFile(file: File) {
		uploading = true;
		try {
			const result = await api.files.upload(pipelineId, file);
			filename = result.filename;
			fileType = result.file_type;

			// Auto-derive table name from filename (unless user manually edited it)
			if (!tableNameManuallyEdited) {
				tableName = deriveTableName(result.filename, otherTableNames);
			}

			saveConfig.cancel();
			saveConfig();
			// Refresh schema after config is saved
			setTimeout(() => fetchSchema(), 600);
			addToast(`Uploaded ${result.filename}`, 'success');
		} catch (e) {
			addToast(`Upload failed: ${e instanceof Error ? e.message : String(e)}`, 'error');
		} finally {
			uploading = false;
		}
	}

	function onFileInput(e: Event) {
		const input = e.target as HTMLInputElement;
		if (input.files?.[0]) handleFile(input.files[0]);
	}

	function onDrop(e: DragEvent) {
		e.preventDefault();
		dragOver = false;
		if (e.dataTransfer?.files?.[0]) handleFile(e.dataTransfer.files[0]);
	}

	function onDragOver(e: DragEvent) {
		e.preventDefault();
		dragOver = true;
	}

	function onDragLeave() {
		dragOver = false;
	}
</script>

<div class="border-t border-gray-200 bg-gray-50/50" data-testid="source-config">
	<div class="space-y-3 p-3">
		<!-- Table name (common to both types) -->
		<div>
			<label class="mb-1 block text-xs font-medium text-gray-600">Table Name</label>
			<input
				class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
				bind:value={tableName}
				oninput={onTableNameInput}
				placeholder="my_table"
			/>
		</div>

		{#if source.type === 'file'}
			<!-- File source config -->
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<div
				class="relative rounded-lg border-2 border-dashed p-3 text-center transition-colors {dragOver
					? 'border-green-400 bg-green-50'
					: 'border-gray-300 hover:border-gray-400'}"
				ondrop={onDrop}
				ondragover={onDragOver}
				ondragleave={onDragLeave}
			>
				{#if uploading}
					<p class="text-sm text-gray-500">Uploading...</p>
				{:else if filename}
					<p class="text-sm font-medium text-gray-700">{filename}</p>
					<p class="text-xs text-gray-400">Drop a new file to replace</p>
				{:else}
					<p class="text-sm text-gray-500">Drop a file here or click to browse</p>
				{/if}
				<input
					type="file"
					class="absolute inset-0 cursor-pointer opacity-0"
					onchange={onFileInput}
					accept=".csv,.tsv,.json,.xlsx,.xls,.parquet"
				/>
			</div>

			{#if fileType === 'csv'}
				<div class="flex gap-3">
					<div class="w-20">
						<label class="mb-1 block text-xs font-medium text-gray-600">Delimiter</label>
						<input
							class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
							bind:value={delimiter}
							oninput={onchange}
						/>
					</div>
					<div class="flex items-end gap-1.5 pb-0.5">
						<input type="checkbox" id="header-{source.id}" bind:checked={hasHeader} onchange={onchange} />
						<label for="header-{source.id}" class="text-xs text-gray-600">Header row</label>
					</div>
				</div>
			{/if}
		{:else}
			<!-- API source config -->
			<div>
				<label class="mb-1 block text-xs font-medium text-gray-600">URL</label>
				<input
					class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
					bind:value={url}
					oninput={onUrlInput}
					placeholder="https://api.example.com/data"
				/>
			</div>

			<div class="w-28">
				<label class="mb-1 block text-xs font-medium text-gray-600">Method</label>
				<select
					class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
					bind:value={method}
					onchange={onchange}
				>
					<option value="GET">GET</option>
					<option value="POST">POST</option>
				</select>
			</div>

			<div>
				<label class="mb-1 block text-xs font-medium text-gray-600">Headers</label>
				<KeyValueEditor bind:entries={headers} keyPlaceholder="Header name" valuePlaceholder="Header value" onchange={onchange} />
			</div>

			{#if method === 'POST'}
				<div>
					<label class="mb-1 block text-xs font-medium text-gray-600">Body</label>
					<textarea
						class="w-full rounded border border-gray-300 px-2 py-1.5 font-mono text-sm focus:border-blue-500 focus:outline-none"
						rows="3"
						bind:value={body}
						oninput={onchange}
						placeholder={'{"key": "value"}'}
					></textarea>
				</div>
			{/if}

			<div>
				<label class="mb-1 block text-xs font-medium text-gray-600">Response Path</label>
				<input
					class="w-full rounded border border-gray-300 px-2 py-1.5 text-sm focus:border-blue-500 focus:outline-none"
					bind:value={responsePath}
					oninput={onchange}
					placeholder="data.results"
				/>
			</div>
		{/if}

		<!-- Schema display -->
		{#if schemaLoading}
			<div class="pt-1">
				<p class="text-xs text-gray-400">Loading schema...</p>
			</div>
		{:else if schemaError}
			<div class="pt-1">
				<p class="text-xs text-red-400">{schemaError}</p>
			</div>
		{:else if schemaColumns.length > 0}
			<div class="pt-1">
				<div class="mb-1 flex items-center justify-between">
					<span class="text-xs font-medium text-gray-600">Schema</span>
					{#if schemaRowCount !== null}
						<span class="text-xs text-gray-400">{schemaRowCount.toLocaleString()} rows</span>
					{/if}
				</div>
				<div class="max-h-48 overflow-y-auto rounded border border-gray-200 bg-white">
					<table class="w-full text-xs">
						<tbody>
							{#each schemaColumns as col, i}
								<tr class={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
									<td class="px-2 py-1 font-medium text-gray-700">{col.name}</td>
									<td class="px-2 py-1 text-right font-mono text-gray-400">{col.type}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{/if}
	</div>
</div>
