// frontend/src/components/Toolbar.tsx
import { useState, useRef, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { usePipelineStore } from '@/stores/pipeline';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

interface ToolbarProps {
  pipelineId: string;
  pipelineName: string;
  onOpenParams: () => void;
  onRun: () => void;
}

export default function Toolbar({ pipelineId, pipelineName, onOpenParams, onRun }: ToolbarProps) {
  const updatePipelineName = usePipelineStore((s) => s.updatePipelineName);
  const [editing, setEditing] = useState(false);
  const [editValue, setEditValue] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editing) inputRef.current?.focus();
  }, [editing]);

  function startEdit() {
    setEditValue(pipelineName);
    setEditing(true);
  }

  function saveName() {
    setEditing(false);
    if (editValue.trim() && editValue !== pipelineName) {
      updatePipelineName(pipelineId, editValue.trim());
    }
  }

  function onKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter') saveName();
    if (e.key === 'Escape') setEditing(false);
  }

  return (
    <div className="flex items-center gap-3 border-b border-gray-200 bg-white px-4 py-2" data-testid="toolbar">
      <Link to="/" className="text-gray-500 hover:text-gray-700" aria-label="Back to pipelines">
        <ArrowLeft className="h-5 w-5" />
      </Link>

      <div className="flex-1">
        {editing ? (
          <input
            ref={inputRef}
            data-testid="pipeline-name-input"
            className="rounded border border-gray-300 px-2 py-1 text-sm font-semibold focus:border-blue-500 focus:outline-none"
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            onKeyDown={onKeyDown}
            onBlur={saveName}
          />
        ) : (
          <button
            data-testid="pipeline-name"
            className="text-sm font-semibold text-gray-800 hover:text-blue-600"
            onClick={startEdit}
          >
            {pipelineName}
          </button>
        )}
      </div>

      <Button variant="outline" size="sm" onClick={onOpenParams}>
        Parameters
      </Button>

      <Button size="sm" onClick={onRun}>
        Run
      </Button>
    </div>
  );
}

// frontend/src/lib/components/Toolbar.svelte
<script lang="ts">
	import { updatePipelineName } from '$lib/stores/pipeline.js';

	let {
		pipelineId,
		pipelineName,
		onOpenParams,
		onOpenRun
	}: {
		pipelineId: string;
		pipelineName: string;
		onOpenParams: () => void;
		onOpenRun: () => void;
	} = $props();

	let editing = $state(false);
	let editValue = $state('');

	function startEdit() {
		editValue = pipelineName;
		editing = true;
	}

	function saveName() {
		editing = false;
		if (editValue.trim() && editValue !== pipelineName) {
			updatePipelineName(pipelineId, editValue.trim());
		}
	}

	function onkeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') saveName();
		if (e.key === 'Escape') editing = false;
	}
</script>

<div class="flex items-center gap-3 border-b border-gray-200 bg-white px-4 py-2" data-testid="toolbar">
	<a href="/" class="text-gray-500 hover:text-gray-700" aria-label="Back to pipelines">
		<svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
			<path d="M19 12H5M12 19l-7-7 7-7" stroke-linecap="round" stroke-linejoin="round" />
		</svg>
	</a>

	<div class="flex-1">
		{#if editing}
			<input
				data-testid="pipeline-name-input"
				class="rounded border border-gray-300 px-2 py-1 text-sm font-semibold focus:border-blue-500 focus:outline-none"
				bind:value={editValue}
				{onkeydown}
				onblur={saveName}
				autofocus
			/>
		{:else}
			<button
				data-testid="pipeline-name"
				class="text-sm font-semibold text-gray-800 hover:text-blue-600"
				onclick={startEdit}
			>
				{pipelineName}
			</button>
		{/if}
	</div>

	<button
		class="rounded border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
		onclick={onOpenParams}
	>
		Parameters
	</button>

	<button
		class="rounded bg-blue-600 px-4 py-1.5 text-sm font-medium text-white shadow hover:bg-blue-700"
		onclick={onOpenRun}
	>
		Run
	</button>
</div>
